/* do not change this file, it is auto generated by storybook. */

import {
  configure,
  addDecorator,
  addParameters,
  addArgsEnhancer,
  clearDecorators,
} from '@storybook/react-native';

import '@storybook/addon-ondevice-controls/register';
import '@storybook/addon-ondevice-actions/register';

import { decorators, parameters } from './preview';

if (decorators) {
  if (__DEV__) {
    // stops the warning from showing on every HMR
    require('react-native').LogBox.ignoreLogs([
      '`clearDecorators` is deprecated and will be removed in Storybook 7.0',
    ]);
  }
  // workaround for global decorators getting infinitely applied on HMR, see https://github.com/storybookjs/react-native/issues/185
  clearDecorators();
  decorators.forEach((decorator) => addDecorator(decorator));
}

if (parameters) {
  addParameters(parameters);
}

try {
  // Auto-load all stories from src directory
  const req = require.context('../src', true, /\.stories\.(tsx?|jsx?)$/);

  configure(() => {
    req.keys().forEach((filename) => req(filename));
  }, module);
} catch (e) {
  console.error('Storybook: Error loading stories:', e);
}

// getStorybookUI is actually from '@storybook/react-native'
import { getStorybookUI } from '@storybook/react-native';

export const view = getStorybookUI({});